// ui/recipe-ui-vue/src/components/ResultsTable.vue
<script>
	import { Grid } from '@progress/kendo-vue-grid';

	export default {
        props: [
            'domain'
        ],
        components: {
            Grid
        },
        data: function () {
            return {
                columns: [
					{
						title: 'Recipe Name',
						field: 'recipeName'
					},
					{
						title: 'Recipe Description',
						field: 'recipeDescription'
					},
                    {
                        title: 'Yield',
                        field: 'recipeYield'
                    }
				],
                data: []
            }
        },
        emits: [
            'gridRowClick'        
        ],
        mounted() {
            fetch(`${this.domain}/recipe`)
                .then(response => response.json())
                .then(data => this.data = data.data.recipe);
        }
    }
</script>
<template>
    <grid
        :data-items="data"
        :columns="columns"
        @rowclick="(e) => $emit('gridRowClick', e.dataItem.recipeId)"
    ></grid>
</template>
<style>
</style>

// ui/recipe-ui-react/src/components/ResultsTable.js
import { useState, useEffect } from 'react';
import { Grid, GridColumn } from '@progress/kendo-react-grid';

export default function ResultsTable({domain, filters}) {
    const [recipes, setData] = useState(null);
    
    useEffect(() => {
        const fetchData = async () => {
            try {
                const response = await fetch(`${domain}/recipe`);
                const json = await response.json();
                setData(json.data.recipes);
            } catch (error) {
                console.error('Error fetching data:', error);
            }
        };
    
        fetchData();
    }, []);

    return (
        <div>
            <Grid data={recipes}>
                <GridColumn field="recipeName" />
                <GridColumn field="recipeDescription" />
                <GridColumn field="difficultyName" />
                <GridColumn field="recipeDuration" />
                <GridColumn field="recipeYield" />
            </Grid>
        </div>
    )
}
