// ui/recipe-ui-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { ProductService } from './product.service';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'recipe-ui-angular';
}

<style>
	.recipeMain {
		text-align: center;

		.built-with {
			display: inline;
		}

		.angular-logo {
			max-width: 10rem;
			vertical-align: middle;
		}
		.kendo-ui-logo {
			max-width: 10rem;
			vertical-align: middle;
		}

		.hosted-on {
			display: inline;
		}

		.docker-logo {
			max-width: 10rem;
			vertical-align: middle;
		}
		.azure-logo {
			max-width: 10rem;
			vertical-align: middle;
		}
	}
</style>

<div class="recipeMain container">
	<div class="row">
		<h1>
			..-recipe-..
		</h1>
	</div>
	<div class="row built-with">
		<span>Built with: </span>
		<span><img class="angular-logo" src="angular-logo.png" /></span>
		<span><img class="kendo-ui-logo" src="kendo-ui-logo.png" /></span>
	</div>
	<br />
	<div class="row hosted-on">
		<span>Hosted on: </span>
		<span><img class="docker-logo" src="docker-logo.png" /></span>
		<span><img class="azure-logo" src="azure-logo.png" /></span>
	</div>
	<div
		class="controls"
	>			
		<div
			class="row text-start"
		>				
			<div
				class="col-sm-4"
			>
				<!---->	
				<dropdowntree
					[domain]="domain"
					[path]="'tag'"
					(dropDownSelect)="handleDropDownSelect($event)"
				/>
				
			</div>
					
			<div
				class="col-sm-4 no-pad-left"
			>					
				<dropdown
					[domain]="domain"
					[path]="'difficulty'"						
					(dropDownSelect)="handleDropDownSelect($event)"
				/>					
			</div> 
			<div
				class="col-sm-4 no-pad-left"
			>
				<dropdown
					[domain]="domain"
					[path]="'duration'"						
					(dropDownSelect)="handleDropDownSelect($event)"
				/>
			</div>
		</div>
	</div>
	<br /> 
	<div
		class="results"
	>
		<results
			[domain]="domain"
		/>
		<!-- <results-table
			:domain="domain"
			:filterCriteria="filterCriteria"
			@gridRowClick="handleGridRowClick"
		/> -->
	</div>
	<!-- <div
		class="edit"
	>
		<div
			class="row"
		>
			<div
				class="col-sm-3"
			>
				<k-button
					@click="toggleNewEditModal"
				>
					New Recipe
				</k-button>
			</div>
			<div
				class="col-sm-3"
			>
				<k-button
					@click="toggleEditTagsModal"
				>
					Edit Tags
				</k-button>
			</div>
			<div
				class="col-sm-3"
			>
				<k-button
					@click="toggleEditIngredientsModal"
				>
					Edit Ingredients
				</k-button>
			</div>
			<div
				class="col-sm-3"
			>
				<k-button
					@click="toggleEditEquipmentsModal"
				>
					Edit Equipment
				</k-button>
			</div>
		</div>
	</div>
	<div
		class="modals"
	>
		<k-window
			v-if="showDisplayModal"
			:initial-width="650"
			:initial-height="700"				
			@close="toggleDisplayModal"
		>
			<display-recipe
				:domain="domain"
				:path="`recipe/${selectedRecipeId}`"
				@editRecipe="handleEditRecipeClick"
			/>
		</k-window>
		<k-window
			v-if="showNewEditModal"
			:initial-width="600"
			:initial-height="825"
			@close="toggleNewEditModal"
		>
			<new-edit-recipe
				:domain="domain"
				:recipeId="selectedRecipeId"
				@close="toggleNewEditModal"
			/>
		</k-window>
		<k-window
			v-if="showEditTagsModal"
			:initial-height="400"
			:initial-width="650"							
			@close="toggleEditTagsModal"
		>
			<edit-items
				:domain="domain"
				:path="'tag'"
			/>
		</k-window>
		<k-window
			v-if="showEditIngredientsModal"
			:initial-height="450"
			:initial-width="650"
			@close="toggleEditIngredientsModal"
		>
			<edit-items
				:domain="domain"
				:path="'ingredient'"
			/>
		</k-window>
		<k-window
			v-if="showEditEquipmentsModal"
			:initial-height="450"
			:initial-width="650"
			@close="toggleEditEquipmentsModal"
		>
			<edit-items
				:domain="domain"
				:path="'equipment'"
			/>
		</k-window>
	</div> -->
</div>
<router-outlet />

// ui/recipe-ui-react/src/App.js
import './App.css';
import { useState } from 'react';
import { Button } from '@progress/kendo-react-buttons';
import { Window } from '@progress/kendo-react-dialogs';

import DropDown from './components/DropDown.js';
import DropDownTree from './components/DropDownTree.js';
import ResultsTable from './components/ResultsTable.js';

import reactLogo from './react-logo.png';
import webpackLogo from './webpack-logo.png';
import bootstrapLogo from './bootstrap-logo.png';
import kendoUiLogo from './kendo-ui-logo.png';

import dockerLogo from './docker-logo.png';
import amazonEcsLogo from './amazon-ecs-logo.png';
import awsLogo from './aws-fargate-logo.png';

const domain = 'http://34.223.67.224:3000';
const filters = null;

function App() {
	const [newEditModal, setNewEditModal] = useState(false);
	const [editEquipmentsModal, setEditEquipmentsModal] = useState(false);
	const [editIngredientsModal, setEditIngredientsModal] = useState(false);
	const [editTagsModal, setEditTagsModal] = useState(false);

	const toggleNewEditModal = () => {
		setNewEditModal(!newEditModal);
	}
	const toggleEditEquipmentsModal = () => {
		setEditEquipmentsModal(!editEquipmentsModal);
	}
	const toggleEditIngredientsModal = () => {
		setEditIngredientsModal(!editIngredientsModal);
	}
	const toggleEditTagsModal = () => {
		setEditTagsModal(!editTagsModal);
	}

	return (
		<div className='App container'>
			<div className='row'>
				<h1>..-recipe-..</h1>
			</div>
			<div className='row built-with'>
				<span>Built with: </span>
				<span><img className='react-logo' src={reactLogo} /></span>
				<span><img className='webpack-logo' src={webpackLogo} /></span>
				<span><img className='bootstrap-logo' src={bootstrapLogo} /></span>
				<span><img className='kendo-ui-logo' src={kendoUiLogo} /></span>
			</div>
			<br />
			<div className='row hosted-on'>
				<span>Hosted on/using: </span>
				<span><img className='docker-logo' src={dockerLogo} /></span>
				<span><img className='amazon-ecs-logo' src={amazonEcsLogo} /></span>
				<span><img className='aws-logo' src={awsLogo} /></span>
			</div>
			<br />
			<div className='row controls'>
				<div className='col-sm-4'>
					<DropDownTree
						domain={domain}
						path='tag'
					/>
				</div>
				<div className='col-sm-4'>
					<DropDown 
						domain={domain}
						path='difficulty'
					/>
				</div>
				<div className='col-sm-4'>
					<DropDown 
						domain={domain}
						path='duration'
					/>
				</div>
			</div>
			<br />
			<div className='row results'>
				<ResultsTable 
					domain={domain}
					filters={filters}
				/>
			</div>
			<br />
			<div className='row edit'>
				<div className='col-sm-3'>
					<Button
						onClick={toggleNewEditModal}
					>
						New Recipe
					</Button>
				</div>
				<div className='col-sm-3'>
					<Button
						onClick={toggleEditEquipmentsModal}
					>
						Edit Equipment
					</Button>
				</div>
				<div className='col-sm-3'>
					<Button
						onClick={toggleEditIngredientsModal}
					>
						Edit Ingredients
					</Button>
				</div>
				<div className='col-sm-3'>
					<Button
						onClick={toggleEditTagsModal}
					>
						Edit Tags
					</Button>
				</div>
			</div>
			<div className='row modals'>
				{
					newEditModal 
					&& 
					<Window
						title='New/Edit Recipe'
						onClose={toggleNewEditModal}
						initialHeight={450}
						initialWidth={650}
					/>
				}
				{
					editEquipmentsModal
					&& 
					<Window
						title='Edit Equipment'
						onClose={toggleEditEquipmentsModal}
						initialHeight={450}
						initialWidth={650}
					/>
				}
				{
					editIngredientsModal 
					&& 
					<Window
						title='Edit Ingredients'
						onClose={toggleEditIngredientsModal}
						initialHeight={450}
						initialWidth={650}
					/>
				}
				{
					editTagsModal 
					&& 
					<Window
						title='Edit Tags'
						onClose={toggleEditTagsModal}
						initialHeight={450}
						initialWidth={650}
					/>
				}
			</div>			
		</div>
	);
}

export default App;
