// ui/recipe-ui-react/src/components/DropDown.js
import { useState, useEffect } from 'react';
import { DropDownList } from '@progress/kendo-react-dropdowns';

export default function DropDown({ domain, path }) {
    const itemId = `${path}Id`;
    const itemName = `${path}Name`;    

    const defaultItem = {};
    defaultItem[itemId] = null;
    defaultItem[itemName] = `Select ${path}...`

    const [dataItems, setData] = useState([]);
    
    useEffect(() => {
        const fetchData = async () => {
            try {
                const response = await fetch(`${domain}/${path}`);
                const json = await response.json();
                setData(json.data[`${path}s`]);
            } catch (error) {
                console.error('Error fetching data:', error);
            }
        };
    
        fetchData();
    }, []);

    const handleChange = (event) => {
        alert(`Selected item text: ${event.target.value[itemName]}, value: ${event.target.value[itemId]}`);
    }

    return (
        <div>
            <DropDownList 
                data={dataItems}
                dataItemKey={itemId}
                defaultItem={defaultItem}
                textField={itemName}                
                onChange={handleChange}
            />                
        </div>
    )
}

// ui/recipe-ui-vue/src/components/DropDown.vue
<script>
    import { DropDownList } from '@progress/kendo-vue-dropdowns';

    export default {
        props: [
            'dataType',
            'domain',
            'path'
        ],
        components: {
            DropDownList
        },
        data: function () {
			const dataObjectName = `${this.dataType}s`;

			const itemId = `${this.dataType}Id`;
			const itemName = `${this.dataType}Name`;

			const defaultItem = {};
			defaultItem[itemId] = null;
			defaultItem[itemName] = `Select ${this.dataType}`;

            return {
				dataObjectName,
				defaultItem,
				itemId,
                itemName,                
                dataItems: []
            }
        },
        emits: [
            'dropDownSelect'        
        ],
        mounted() {
            fetch(`${this.domain}/${this.path}`)
                .then(response => response.json())
                .then(data => this.dataItems = data.data[this.dataObjectName]);
        }
    }

</script>
<template>
    <drop-down-list
  		:data-items="dataItems"
		:data-item-key="itemId"
		:text-field="itemName"
		:default-item="this.defaultItem"
		@change="(e) => $emit('dropDownSelect', { dataType: this.dataType, id: e.target.value[itemId], name: e.target.value[itemName] })"
    />
</template>
