// ui/recipe-ui-react/src/components/EditItems.js
import { TextBox, TextArea } from '@progress/kendo-react-inputs';
// import { useState, useEffect } from 'react';
// import { DropDownList } from '@progress/kendo-react-dropdowns';

export default function EditItems({ domain, path }) {
    // const itemId = `${path}Id`;
    // const itemName = `${path}Name`;    

    // const defaultItem = {};
    // defaultItem[itemId] = null;
    // defaultItem[itemName] = `Select ${path}...`

    // const [dataItems, setData] = useState([]);
    
    // useEffect(() => {
    //     const fetchData = async () => {
    //         try {
    //             const response = await fetch(`${domain}/${path}`);
    //             const json = await response.json();
    //             setData(json.data[`${path}s`]);
    //         } catch (error) {
    //             console.error('Error fetching data:', error);
    //         }
    //     };
    
    //     fetchData();
    // }, []);

    // const handleChange = (event) => {
    //     alert(`Selected item text: ${event.target.value[itemName]}, value: ${event.target.value[itemId]}`);
    // }

    return (
        <div className='container'>
            <div className='row'>
                <h3>Add / Edit {path}s</h3>            
            </div>
            <br />
            <form className="border" onSubmit={saveParent}>
                <div className='row'>
                    <div className='col-sm-5 text-start'>                    
                        New top level {path}
                    </div>
                    <div className='col-sm-5'>
                        <TextBox
                            value={newParent}
                        />
                    </div>
                    <div className='col-sm-2'>
                        <Button
                            type='submit'
                        >
                            Save
                        </Button>
                    </div>
                </div>
                <br />
                <div className='row'>
                    <div className='col-sm-5 text-start'>                    
                        New sub level {path}
                    </div>
                    <div className='col-sm-5'>
                        <TextBox
                            value={newChild}
                        />
                    </div>
                    <div className='col-sm-2'>
                        <Button
                            type='submit'
                        >
                            Save
                        </Button>
                    </div>
                </div>
            </form>
                        
        </div>
    )
}

// ui/recipe-ui-vue/src/components/EditItems.vue
<script>
    import { Button as KButton } from '@progress/kendo-vue-buttons';
    import { 
        Switch as KSwitch,
        TextBox as KTextBox
    } from "@progress/kendo-vue-inputs";
    import DropDownTree from './DropDownTree.vue';
    
    export default {
        props: [
            'domain',
            'path'
        ],
        components: {
            DropDownTree,
            KButton,
            KSwitch,
            KTextBox
        },
        computed: {
            treeData () {
                return processTreeData(this.dataItems, { expanded: this.expanded, value: this.value }, fields);
            }
        },
        data: function() {
            return {
                checked: true,
                selectedItemId: undefined
            }
        },
        emits: [],
        methods: {
            itemSelected (e) {
                alert(`item selected ${e.selectedItemId}`);
                this.selectedItemId = e.selectedItemId;
            },
            saveParent (e) {
                e.preventDefault();

				alert(`Form Submitted ${this.parent}`);

				fetch(`${this.domain}/tag/${this.parent}`, {
					method: 'put'
				})
			},
            saveUpdateChild (e) {
                e.preventDefault();

				alert(`Form Submitted ${this.child} ${this.selectedItemId} ${this.checked}`);

                if (this.checked) {
                    fetch(`${this.domain}/tag/${this.selectedItemId}/${this.child}`, {
                        method: 'put'
                    });
                } else {
                    fetch(`${this.domain}/tag/${this.selectedItemId}/${this.child}`, {
                        method: 'post'
                    });
                }				
            }
        }
    }
</script>
<template>
    <div
        class="container"
    >
        <div
            class="row"
        >
            <h3>{{ `Add / Edit ${this.path}s` }}</h3>
        </div>
        <br />
        <form
            class="border"
            @submit="saveParent"
        >
            <div
                class="row"
            >
                <div
                    class="col-sm-5 text-start"
                >
                    {{ `New top level ${this.path}` }}
                </div>
                <div
                    class="col-sm-5"
                >
                    <k-text-box
                        v-model="parent"
                    />
                </div>
                <div
                    class="col-sm-2"
                >
                    <k-button
                        type="submit"
                    >
                        Save
                    </k-button>
                </div>
            </div>
        </form>
        <br />
        <div
            class="border"
        >
            <div
                class="row"
            >
                <div
                    class="col-sm-10"
                >
                    <k-switch
                        :checked="checked"
                        :default-checked="true"
                        :style="{ width: '100%' }"
                        :on-label="`Add a child ${this.path} to this ${this.path} group`"
                        :off-label="`Update this ${this.path} to the new value specified`"
                        
                        @change="(e) => this.checked = !this.checked"
                    />
                </div>
                <div
                    class="col-sm-2"
                >
                </div>                
            </div>
            <form
                @submit="saveUpdateChild"
            >            
                <br />
                <div
                    class="row"
                >
                    <div
                        class="col-sm-5"
                    >                    
                        <DropDownTree
                            :domain="domain"
                            :path="path"
                            @itemSelected="itemSelected"
                        />
                    </div>
                    <div
                        class="col-sm-5"
                    >
                        <k-text-box
                            v-model="child"
                        />
                    </div>
                    <div
                        class="col-sm-2"
                    >
                        <k-button
                            type="submit"
                        >
                            Save
                        </k-button>
                    </div>
                </div>      
            </form>
        </div>        
    </div>    
</template>
<style scoped>
    .border {
        border-color: grey;
        border-radius: 25px;
        border-style: solid;
        border-width: 1px;
        padding: 20px;
    }
</style>
